### ISSUE TITLE
发生运行时错误：RuntimeError: Error(s) in loading state_dict for Tacotron2

### ISSUE THREAD

**Issue by 6DDUU6** [luoyily/MoeTTS#16]
v1.1.1
![image](https://user-images.githubusercontent.com/51308585/184521582-d16d1a13-8adf-4337-bcf4-63b81a7ccc0e.png)

**Comment by luoyily** [comment]
你的模型是否训练时使用的非官方符号表（symbols），如果是，请见readme 自定义Cleaner与Symbols部分

**Comment by 6DDUU6** [comment]
> 你的模型是否训练时使用的非官方符号表（symbols），如果是，请见readme 自定义Cleaner与Symbols部分

好的谢谢，解决了
