### ISSUE TITLE
使用工具箱转换分词+调形时报错

### ISSUE THREAD

**Issue by mirrorange** [luoyily/MoeTTS#17]
尝试使用工具箱中分词+调形功能时报错：

Traceback (most recent call last):
  File "japanese_g2p.py", line 116, in <module>
UnicodeEncodeError: 'gbk' codec can't encode character '\u0283' in position 0: illegal multibyte sequence
[12176] Failed to execute script 'japanese_g2p' due to unhandled exception!

选择其它选项转换均正常。

![分词+调形报错](https://user-images.githubusercontent.com/36698236/186292602-2fc0cdf6-d33b-44f1-8c10-3be0cafa00e9.png)

软件版本：v1.1.1
操作系统：Windows 10 20H2
系统语言：中文（简体，中国）

**Comment by luoyily** [comment]
这个错误可能由pyinstaller打包的解释器编码默认为gbk导致, 你可以暂时在 “Windows设置-语言与区域-高级” 中找到“beta全球化支持”，并勾选他来解决。后续版本会尝试将pyopenjtalk内置或修复编码问题。

**Comment by luoyily** [comment]
此问题已修复，需要可以下载新版
