### ISSUE TITLE
希望中文支持

### ISSUE THREAD

**Issue by ycfeng666** [luoyily/MoeTTS#18]
或者小工具可以将汉字直接转换为罗马音

**Comment by luoyily** [comment]
不知道你指的是能转换日语中汉字，还是自动翻译中文到日语再到罗马音，还是中文音译到罗马音？

**Comment by ycfeng666** [comment]
> 不知道你指的是能转换日语中汉字，还是自动翻译中文到日语再到罗马音，还是中文音译到罗马音？

目前直接说中文可能比较困难，我想输入中文转成罗马音后再输出实现讲述中文

**Comment by luoyily** [comment]
此功能不会被加入。你可以将中文与日语数据集同时作为VITS多人模型训练，利用VC功能转换。不推荐通过音译合成中文，如果仍然想要音译，你可以直接在文本框中自行输入音译后合成。
如果你不会日语也不会发音，可以使用以下音译工具，不保证可用性。
https://www.ltool.net/chinese-simplified-and-traditional-characters-pinyin-to-katakana-converter-in-simplified-chinese.php
