### ISSUE TITLE
httpapi开发进度

### ISSUE THREAD

**Issue by ghost** [luoyily/MoeTTS#19]
您好，请问httpapi是否还在开发吗？

如果没有，我打算用docker包装一个vits的api，可以直接pr一个新分支吗 ？

**Comment by luoyily** [comment]
我是打算打包为可执行文件，用docker的话，用户还需下载个docker
关于开发进度，我这边是优先更新GUI，HttpApi最近才准备开始，可能进度会比较慢。

**Comment by ghost** [comment]
windows下pyopenjtalk不太会（，而且感觉都api了也不太可能部署在本地了吧
